// types.js

export const GET_ERRORS = 'GET_ERRORS';
export const GET_ERROR_TOAST = 'GET_ERROR_TOAST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CURRENT_USER_INFO = 'CURRENT_USER_INFO';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const OPEN_PROJECT_MODAL = 'OPEN_PROJECT_MODAL';
export const CLOSE_PROJECT_MODAL = 'CLOSE_PROJECT_MODAL';
export const OPEN_DEVICE_MODAL = 'OPEN_DEVICE_MODAL';
export const CLOSE_DEVICE_MODAL = 'CLOSE_DEVICE_MODAL';
export const OPEN_THING_MODAL = 'OPEN_THING_MODAL';
export const CLOSE_THING_MODAL = 'CLOSE_THING_MODAL';
export const NEW_PROJECT_CREATED = 'NEW_PROJECT_CREATED';
export const NEW_DEVICE_CREATED = 'NEW_DEVICE_CREATED';
export const NEW_THING_CREATED = 'NEW_THING_CREATED';
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
